# Generated by Django 4.1.7 on 2023-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=50, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('dataNascimento', models.DateField(verbose_name='data nascimento')),
                ('telefone', models.CharField(max_length=12, verbose_name='telefone')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('endereco', models.CharField(max_length=100, verbose_name='endereco')),
                ('estadoCivil', models.CharField(max_length=20, verbose_name='estado civil')),
                ('ctps', models.IntegerField()),
                ('pis', models.IntegerField()),
                ('nomePai', models.CharField(max_length=50)),
                ('nomeMae', models.CharField(max_length=50)),
                ('tipoVinculo', models.CharField(max_length=20)),
                ('cargoAtual', models.CharField(max_length=20)),
                ('funcaoAtual', models.CharField(max_length=20)),
                ('salarioAtual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dataAdmissao', models.DateField()),
                ('dataDesligamento', models.DateField(null=True)),
                ('situacaoVinculo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
