# Generated by Django 4.2.2 on 2023-06-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=50, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('dataNascimento', models.DateField(verbose_name='data nascimento')),
                ('telefone', models.CharField(max_length=12, verbose_name='telefone')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('endereco', models.CharField(max_length=100, verbose_name='endereco')),
                ('estadoCivil', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('O', 'Outro')], max_length=1)),
                ('ctps', models.IntegerField()),
                ('pis', models.IntegerField()),
                ('nomePai', models.CharField(max_length=50, verbose_name='Pai')),
                ('nomeMae', models.CharField(max_length=50, verbose_name='Mae')),
                ('tipoVinculo', models.CharField(choices=[('E', 'Experiencia'), ('C', 'Contratado')], max_length=1, verbose_name='Tipo vinculo')),
                ('cargoAtual', models.CharField(choices=[('V', 'vendedor'), ('S', 'supervisor'), ('G', 'gerente')], max_length=1, verbose_name='Cargo atual')),
                ('funcaoAtual', models.CharField(choices=[('N', 'Normal'), ('C', 'Comissionada')], max_length=1, verbose_name='Funcao atual')),
                ('salarioAtual', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salario atual')),
                ('dataAdmissao', models.DateField(verbose_name='Admissao')),
                ('dataDesligamento', models.DateField(null=True, verbose_name='Desligamento')),
                ('situacaoVinculo', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Situacao  vinculo')),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
                'permissions': (('permissao_gerente', 'permissao gerente'), ('permissao_supervisor', 'permissao supervisor'), ('permissao_vendedor', 'permissao vendedor'), ('permissao_funcionario', 'permissao todos funcionarios')),
            },
        ),
    ]
