# Generated by Django 4.1.7 on 2023-03-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='dataDemissao',
            new_name='dataDesligamento',
        ),
    ]
