# Generated by Django 4.2.2 on 2023-06-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='dataDesligamento',
            field=models.DateField(blank=True, null=True, verbose_name='Desligamento'),
        ),
    ]
