# Generated by Django 4.1.7 on 2023-03-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='dataDesligamento',
            field=models.DateField(null=True),
        ),
    ]
