# Generated by Django 4.1.7 on 2023-06-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_alter_colaborador_datadesligamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name_plural': 'Colaboradores'},
        ),
    ]
