# Generated by Django 4.1.7 on 2023-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_rename_datademissao_colaborador_datadesligamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='situacaoVinculo',
            field=models.CharField(max_length=20),
        ),
    ]
