# Generated by Django 4.1.7 on 2023-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_alter_colaborador_estadocivil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='situacaoVinculo',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1),
        ),
    ]
