# Generated by Django 4.1.7 on 2023-06-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_alter_colaborador_situacaovinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargoAtual',
            field=models.CharField(choices=[('V', 'vendedor'), ('S', 'supervisor'), ('G', 'gerente')], max_length=1),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='funcaoAtual',
            field=models.CharField(choices=[('N', 'Normal'), ('C', 'Comissionada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipoVinculo',
            field=models.CharField(choices=[('E', 'Experiencia'), ('C', 'Contratado')], max_length=1),
        ),
    ]
