# Generated by Django 4.1.7 on 2023-06-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_alter_colaborador_datanascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(max_length=12, verbose_name='telefone'),
        ),
    ]
