# Generated by Django 4.1.7 on 2023-06-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_alter_colaborador_cargoatual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargoAtual',
            field=models.CharField(choices=[('V', 'vendedor'), ('S', 'supervisor'), ('G', 'gerente')], max_length=1, verbose_name='Cargo atual'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='dataAdmissao',
            field=models.DateField(verbose_name='Admissao'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='dataDesligamento',
            field=models.DateField(null=True, verbose_name='Desligamento'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='funcaoAtual',
            field=models.CharField(choices=[('N', 'Normal'), ('C', 'Comissionada')], max_length=1, verbose_name='Funcao atual'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nomeMae',
            field=models.CharField(max_length=50, verbose_name='Mae'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nomePai',
            field=models.CharField(max_length=50, verbose_name='Pai'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='salarioAtual',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salario atual'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='situacaoVinculo',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Situacao  vinculo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipoVinculo',
            field=models.CharField(choices=[('E', 'Experiencia'), ('C', 'Contratado')], max_length=1, verbose_name='Tipo vinculo'),
        ),
    ]
