version: '3'

services:
  app:
    build: .
    container_name: cont_django_concessionaria
    user: "1001:1001"
    volumes:
      - .:/home/python/app
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "7000:7000"
    command: ./start.sh