# Generated by Django 4.1.7 on 2023-03-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('endereco', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=20)),
            ],
        ),
    ]
