# Generated by Django 4.1.7 on 2023-03-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMarca', models.CharField(max_length=20)),
                ('cpnjMarca', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFornecedor', models.CharField(max_length=20)),
                ('cnpjFornecedor', models.CharField(max_length=14)),
                ('emailFornecedor', models.EmailField(max_length=254)),
                ('enderecoFornecedor', models.CharField(max_length=100)),
                ('marcaFornecida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.marcas')),
            ],
        ),
    ]
