# Generated by Django 4.1.7 on 2023-03-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedores',
            new_name='Fornecedor',
        ),
        migrations.RenameModel(
            old_name='Marcas',
            new_name='Marca',
        ),
    ]
