# Generated by Django 4.1.7 on 2023-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_rename_fornecedores_fornecedor_rename_marcas_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='nomeFornecedor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nomeMarca',
            field=models.CharField(max_length=30),
        ),
    ]
