# Generated by Django 4.1.7 on 2023-03-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_nomefornecedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='cpnjMarca',
            new_name='cnpjMarca',
        ),
    ]
