# Generated by Django 4.2.2 on 2023-06-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carros', '0001_initial'),
        ('colaboradores', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField()),
                ('detalhes', models.CharField(max_length=50)),
                ('valorVenda', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('formaPagamento', models.CharField(choices=[('e', 'especie'), ('t', 'transferencia bancaria'), ('c', 'consorcio')], max_length=1, verbose_name='Pagamento')),
                ('situacao', models.CharField(choices=[('P', 'processada'), ('C', 'cancelada'), ('F', 'finalizada')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colaboradores.colaborador')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.versao')),
            ],
        ),
    ]
