# Generated by Django 4.1.7 on 2023-06-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='formaPagamento',
            field=models.CharField(choices=[('e', 'especie'), ('t', 'transferencia bancaria'), ('c', 'consorcio')], max_length=1, verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valorVenda',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor'),
        ),
    ]
