# Generated by Django 4.1.7 on 2023-04-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='situacao',
            field=models.CharField(choices=[('P', 'processada'), ('C', 'cancelada'), ('F', 'finalizada')], default='f', max_length=1),
            preserve_default=False,
        ),
    ]
