# Generated by Django 4.1.7 on 2023-03-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_nomefornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('nomeCarro', models.CharField(max_length=30)),
                ('combustivelCarro', models.CharField(max_length=20)),
                ('especificacaoCarro', models.CharField(max_length=100)),
                ('anoFabricacaoCarro', models.IntegerField()),
                ('anoModeloCarro', models.IntegerField()),
                ('chassiCarro', models.CharField(max_length=17)),
                ('marcaCarro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.marca')),
            ],
        ),
    ]
