# Generated by Django 4.1.7 on 2023-06-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('slugCarro', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'permissions': (('permissao_gerente', 'permissao gerente'), ('permissao_supervisor', 'permissao supervisor'), ('permissao_vendedor', 'permissao vendendor'), ('permissao_funcionario', 'permissao todos funcionarios')),
            },
        ),
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Combustiveis',
            },
        ),
        migrations.CreateModel(
            name='Direcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Direcoes',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cv', models.IntegerField()),
                ('torque', models.FloatField()),
                ('rpm', models.IntegerField()),
                ('valvulas', models.IntegerField()),
                ('cilindros', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name_plural': 'Motores',
            },
        ),
        migrations.CreateModel(
            name='Seguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='carros')),
                ('ano', models.IntegerField(default='2023')),
                ('modelo', models.IntegerField(default='2023')),
                ('estoque', models.IntegerField(default=0)),
                ('slugVersao', models.SlugField(blank=True, null=True, unique=True)),
                ('acessorio', models.ManyToManyField(blank=True, related_name='versao_acessorio', to='carros.acessorio')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.carro')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.combustivel')),
                ('direcao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.direcao')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.motor')),
                ('seguranca', models.ManyToManyField(blank=True, related_name='versao_seguranca', to='carros.seguranca')),
            ],
            options={
                'verbose_name_plural': 'Versoes',
            },
        ),
    ]
