# Generated by Django 4.2.2 on 2023-06-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={},
        ),
    ]
