# Generated by Django 4.1.7 on 2023-03-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='placa',
            new_name='placaCarro',
        ),
    ]
