# Generated by Django 4.1.7 on 2023-04-17 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_carro_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cv', models.IntegerField()),
                ('torque', models.FloatField()),
                ('rpm', models.IntegerField()),
                ('valvulas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='carro',
            old_name='nomeCarro',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='anoFabricacaoCarro',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='anoModeloCarro',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='chassiCarro',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='combustivelCarro',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='especificacaoCarro',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='placaCarro',
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='carros')),
                ('estoque', models.IntegerField(default=0)),
                ('acessorios', models.ManyToManyField(blank=True, null=True, related_name='versao_acessorios', to='carros.acessorio')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.carro')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.combustivel')),
                ('direcao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.direcao')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.motor')),
            ],
        ),
    ]
