# Generated by Django 4.2.2 on 2023-06-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_alter_carro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versao',
            name='ano',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='versao',
            name='modelo',
            field=models.IntegerField(default=2023),
        ),
    ]
