# Generated by Django 4.1.7 on 2023-04-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_acessorio_combustivel_direcao_motor_seguranca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versao',
            name='acessorios',
            field=models.ManyToManyField(blank=True, related_name='versao_acessorios', to='carros.acessorio'),
        ),
    ]
