# Generated by Django 4.1.7 on 2023-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_motor_cilindros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versao',
            name='acessorios',
        ),
        migrations.AddField(
            model_name='versao',
            name='acessorio',
            field=models.ManyToManyField(blank=True, related_name='versao_acessorio', to='carros.acessorio'),
        ),
        migrations.AddField(
            model_name='versao',
            name='seguranca',
            field=models.ManyToManyField(blank=True, related_name='versao_seguranca', to='carros.seguranca'),
        ),
    ]
