# Generated by Django 4.1.7 on 2023-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_remove_versao_acessorios_versao_acessorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versao',
            name='slugVersao',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
