# Generated by Django 4.1.7 on 2023-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0007_versao_slugversao_alter_carro_nome_alter_versao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='slugCarro',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
