# Generated by Django 4.1.7 on 2023-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0012_versao_ano_versao_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combustivel',
            options={'verbose_name_plural': 'Combustiveis'},
        ),
        migrations.AlterModelOptions(
            name='direcao',
            options={'verbose_name_plural': 'Direcoes'},
        ),
        migrations.AlterModelOptions(
            name='motor',
            options={'verbose_name_plural': 'Motores'},
        ),
        migrations.AlterModelOptions(
            name='versao',
            options={'verbose_name_plural': 'Versoes'},
        ),
        migrations.AlterField(
            model_name='versao',
            name='ano',
            field=models.IntegerField(default='2023'),
        ),
        migrations.AlterField(
            model_name='versao',
            name='modelo',
            field=models.IntegerField(default='2023'),
        ),
    ]
