# Generated by Django 4.1.7 on 2023-06-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0013_alter_combustivel_options_alter_direcao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'permissions': (('permissao_gerente', 'permissao gerente'), ('permissao_vendedor', 'permissao vendendor'), ('permissao_funcionario', 'permissao todos funcionarios'))},
        ),
        migrations.AlterField(
            model_name='versao',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.carro'),
        ),
    ]
