# Generated by Django 4.1.7 on 2023-06-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0014_alter_carro_options_alter_versao_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versao',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carros.carro'),
        ),
    ]
