# Generated by Django 4.2.2 on 2023-06-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=50, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('dataNascimento', models.DateField(verbose_name='data nascimento')),
                ('telefone', models.CharField(max_length=12, verbose_name='telefone')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('endereco', models.CharField(max_length=100, verbose_name='endereco')),
                ('estadoCivil', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('O', 'Outro')], max_length=1)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='renda')),
                ('profissao', models.CharField(max_length=20, verbose_name='profissao')),
            ],
            options={
                'permissions': (('permissao_gerente', 'permissao gerente'), ('permissao_supervisor', 'permissao supervisor'), ('permissao_vendedor', 'permissao vendedor'), ('permissao_funcionario', 'permissao todos funcionarios')),
            },
        ),
    ]
