# Generated by Django 4.1.7 on 2023-06-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dataNascimento',
            field=models.DateField(verbose_name='data nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(max_length=20, verbose_name='estado civil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomeCompleto',
            field=models.CharField(max_length=50, verbose_name='nome completo'),
        ),
    ]
