# Generated by Django 4.1.7 on 2023-06-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_datanascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(max_length=20, verbose_name='profissao'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='renda',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='renda'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=12, verbose_name='telefone'),
        ),
    ]
