# Generated by Django 4.1.7 on 2023-06-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_cpf_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('permissao_gerente', 'permissao gerente'), ('permissao_vendedor', 'permissao vendendor'), ('permissao_funcionario', 'permissao todos funcionarios'))},
        ),
    ]
