# Generated by Django 4.1.7 on 2023-06-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('permissao_gerente', 'permissao gerente'), ('permissao_supervisor', 'permissao supervisor'), ('permissao_vendedor', 'permissao vendendor'), ('permissao_funcionario', 'permissao todos funcionarios'))},
        ),
    ]
