# Generated by Django 4.1.7 on 2023-04-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0011_alter_versao_imagem'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='carro',
        ),
        migrations.AddField(
            model_name='compra',
            name='versao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carros.versao'),
        ),
    ]
