# Generated by Django 4.2.2 on 2023-06-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'permissions': (('permissao_gerente', 'permissao gerente'), ('permissao_supervisor', 'permissao supervisor'), ('permissao_vendedor', 'permissao vendedor'), ('permissao_funcionario', 'permissao todos funcionarios'))},
        ),
    ]
